//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace populat.io
{
    using System;
    using System.Collections.Generic;
    
    public partial class PopulationTable
    {
        public string City { get; set; }
        public double Age0_17 { get; set; }
        public double Age18_34 { get; set; }
        public double Age35_54 { get; set; }
        public double Age55_Up { get; set; }
        public double AverageAge { get; set; }
        public double BirthRate { get; set; }
        public double DeathRate { get; set; }
        public double EmigrationRate { get; set; }
        public double ImmigrationRate { get; set; }
        public double FemaleRate { get; set; }
        public double MaleRate { get; set; }
        public double GrowthRate { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double PopulationNr { get; set; }
        public int Year { get; set; }
    }
}
